
class VitalGraphServiceConstants:

    SERVICE_GRAPH_URI = "urn:SERVICE_GRAPH"

    ONTOLOGY_GRAPH_URI = "urn:ONTOLOGY_GRAPH"

    SERVICE_GRAPH_ID = "SERVICE_GRAPH"

    ONTOLOGY_GRAPH_ID = "ONTOLOGY_GRAPH"

    GLOBAL_INFIX = "GLOBAL"

